name: HGVMOF
channels:
  - conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - python=3.9.21
  - jupyter=1.1.1
  - tqdm=4.67.1
  - pandas=2.2.3
  - matplotlib=3.9.2
  - scikit-learn=1.6.1
  - rdkit=2024.3.5
  - numpy=1.26.3
  - scipy=1.13.1
  - torch=2.6.0+cu118
  - ipykernel=6.29.5